server:
  port: 8080

spring:
  application:
    name: iot-backend
  datasource:
    url: jdbc:mysql://localhost:3307/iot_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: iot
    password: iot123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

influx:
  url: http://localhost:8086
  user: admin
  password: admin123
  org: iot-org
  bucket: iot-bucket
  token: iot-token

emqx:
  host: localhost
  port: 1883
  username: emqx
  password: public

# 其他配置可根据实际环境调整
