INSERT INTO product_category (id, name, code, parent_id, create_time, update_time) VALUES
(1, '智能城市', 'SmartCity', NULL, now(), now()),
(2, '公共服务', 'PublicService', 1, now(), now()),
(3, '路灯照明', 'Lighting', 2, now(), now()),
(15, '能源管理', 'EnergyMangement', 1, now(), now()),
(16, '环境感知', 'EnvironmentalPerception', 1, now(), now()),
(17, '消防安全', 'FireSafety', 1, now(), now()),
(18, '种植养殖', 'Farming', 1, now(), now()),
(19, '智能楼宇', 'SmartBuilding', 1, now(), now()),
(20, '电表', 'ElectricityMeter', 15, now(), now()),
(21, '水表', 'WaterMeter', 15, now(), now()),
(22, '空调', 'AirConditioner', 16, now(), now()),
(23, '环境监测设备', 'EnvironmentMonitor', 16, now(), now()),
(24, '安防监测网关', 'SecurityGateway', 17, now(), now()),
(25, '烟雾探测器', 'SmokeDetector', 17, now(), now()),
(28, '蓝牙秤', 'BlueToothScale', 19, now(), now()),
(31, '活动检测设备', 'ActivityDetectionEquipment', 16, now(), now()),
(32, '灯光设备', 'LightingFacility', 19, now(), now()),
(33, '大气监测设备', 'AirCollect', 16, now(), now()),
(34, '声光报警设备', 'AcoustoOpticalarm', 17, now(), now()),
(35, '饮水机', 'DrinkingFoundation', 19, now(), now()),
(36, '喷灌智能终端', 'SmartSprinklerTerminal', 18, now(), now()),
(38, '井盖', 'ManholeCover', 17, now(), now()),
(40, '农业监控设备', 'AgriculturalMonitor', 18, now(), now()),
(41, '智能生活', 'SmartLife', NULL, now(), now()),
(42, '家居安防', 'HomeSecurity', 41, now(), now()),
(43, '燃气报警器', 'GasDetector', 42, now(), now()),
(44, '水浸报警器', 'WaterDetector', 42, now(), now()),
(45, '智能工业', 'SmartIndustry', NULL, now(), now()),
(46, '纺织业', 'TextileIndustry', 45, now(), now()),
(47, '医药制造业', 'PharmaceuticalManufacturing', 45, now(), now()),
(48, '塑料制品业', 'PlasticProductsIndustry', 45, now(), now()),
(49, '金属制品业', 'MetalProductsIndustry', 45, now(), now()),
(50, '化学纤维制造业', 'ChemicalFiberManufacturing', 45, now(), now()),
(51, '红外探测器', 'IRDetector', 42, now(), now()),
(52, '门磁传感器', 'DoorContact', 42, now(), now()),
(53, '烟雾报警器', 'SmokeAlarm', 42, now(), now()),
(54, '环境电器', 'Environment', 41, now(), now()),
(55, '风扇', 'Fan', 54, now(), now()),
(56, '加湿器', 'Humidifier', 54, now(), now()),
(57, '取暖器', 'Heater', 54, now(), now()),
(58, '电工照明', 'Electrical&Lighting', 41, now(), now()),
(59, '灯', 'Light', 58, now(), now()),
(60, '插座', 'Outlet', 58, now(), now()),
(61, '窗帘', 'Curtain', 58, now(), now()),
(62, '空气盒子', 'Airbox', 54, now(), now()),
(63, '大家电', 'MajorAppliance', 41, now(), now()),
(64, '冰箱', 'Fridge', 63, now(), now()),
(65, '除湿器', 'Dehumidifier', 54, now(), now()),
(66, '厨房电器', 'KitchenAppliance', 41, now(), now()),
(67, '油烟机', 'KitchenVentilator', 66, now(), now()),
(68, '个护健康', 'Health', 41, now(), now()),
(69, '足浴盆', 'FootBath', 68, now(), now()),
(70, '推窗器', 'WindowLinearActuator', 58, now(), now()),
(71, '入墙开关', 'WallSwitch', 58, now(), now()),
(72, '新风机', 'FAU', 54, now(), now()),
(73, '电热毯', 'ElectricBlanket', 68, now(), now()),
(74, '地暖', 'FloorHeating', 54, now(), now()),
(75, '电热水器', 'ElectricWaterHeater', 63, now(), now()),
(76, '车辆定位卡', 'Locater', 2, now(), now()),
(77, '激光探测仪', 'LaserScanner', 17, now(), now()),
(78, '其它', 'Others', 41, now(), now()),
(79, '浴霸', 'BathHeater', 78, now(), now()),
(80, '燃气灶', 'Stove', 66, now(), now()),
(81, '燃气热水器', 'GasWaterHeater', 63, now(), now()),
(82, '净水器', 'WaterPurifier', 54, now(), now()),
(83, '空气净化器', 'AirPurifier', 54, now(), now()),
(84, '空调机', 'AirConditioning', 63, now(), now()),
(85, '手环', 'Wristband', 68, now(), now()),
(87, '边缘计算', 'LinkEdge', NULL, now(), now()),
(88, '边缘网关', 'gateway', 87, now(), now()),
(89, '其他设备', 'other', 87, now(), now()),
(92, '床', 'Bed', 68, now(), now()),
(95, '晾衣杆', 'Airer', 78, now(), now()),
(96, '浴缸', 'Bathtub', 78, now(), now()),
(97, '淋浴房', 'ShowerRoom', 78, now(), now()),
(98, '干蒸房', 'Sauna', 78, now(), now()),
(99, '马桶', 'ToiletSeat', 78, now(), now()),
(100, '用水监控器', 'WaterMonitor', 42, now(), now()),
(102, '商业共享', 'linkbusiness', NULL, now(), now()),
(103, '零售设备', 'retail', 102, now(), now()),
(104, '共享租赁服务', 'sharing', 102, now(), now()),
(105, '果汁机', 'Juicer', 103, now(), now()),
(106, '网络设备', 'Networking', 41, now(), now()),
(107, '网关', 'GeneralGateway', 106, now(), now()),
(109, '净水机', 'Water purifier', 103, now(), now()),
(110, '冰淇淋机', 'Ice cream machine', 103, now(), now()),
(111, '咖啡机', 'Coffee machine', 103, now(), now()),
(112, '售货柜', 'Containers', 103, now(), now()),
(113, '抓娃娃机', 'Grab the doll machine', 103, now(), now()),
(114, '按摩椅', 'Massage chair', 104, now(), now()),
(115, '共享洗衣机', 'Shared washing machine', 104, now(), now()),
(116, '香薰机', 'AromaDiffuser', 54, now(), now()),
(117, '智能模板', 'SmartTemplate', NULL, now(), now()),
(118, 'Wifi功能模板', 'WifiTemplate', 117, now(), now()),
(119, 'Zigbee功能模板', 'ZigbeeTemplate', 117, now(), now()),
(120, '智能门锁', 'SmartDoor', 42, now(), now()),
(121, '充电桩', 'Charging pile', 104, now(), now()),
(122, '光照度传感器', 'IlluminationSensor', 42, now(), now()),
(123, '场景开关', 'SceneSwitch', 58, now(), now()),
(124, '声光报警器', 'Siren', 42, now(), now()),
(125, '洗碗机', 'DishWasher', 66, now(), now()),
(130, '破壁机', 'BreakingMachine', 66, now(), now()),
(131, '微波炉', 'MicrowaveOven', 66, now(), now()),
(132, '电饭煲', 'RiceCooker', 66, now(), now()),
(133, '酸碱度监测', 'PHSensor', 16, now(), now()),
(134, '溶解氧监测', 'DOSensor', 16, now(), now()),
(135, '燃气泄漏报警器', 'GasLeakAlarm', 17, now(), now()),
(136, '消防手报', 'FireButton', 17, now(), now()),
(137, '水压传感器', 'WaterPressureSensor', 17, now(), now()),
(138, '水浸检测', 'WaterloggingSensor', 2, now(), now()),
(139, '井盖移位检测', 'ManholesCoverShiftDetection', 2, now(), now()),
(140, '垃圾满溢检测', 'GarbageOverflowingDetection', 2, now(), now()),
(141, '地磁检测器', 'GeomagneticSensor', 2, now(), now()),
(142, '红外体征探测器', 'InfraredDetectors', 2, now(), now()),
(143, '红外对射探测器', 'ActiveInfraredIntrusionDetectors', 2, now(), now()),
(144, '无人机', 'UnmannedAerialVehicle', 2, now(), now()),
(145, '门磁', 'DoorSensor', 2, now(), now()),
(146, '调奶器', 'MilkModulator', 66, now(), now()),
(147, '跑步机', 'Threadmill', 68, now(), now()),
(148, '摄像头', 'Camera', 42, now(), now()),
(150, '门铃', 'Doorbell', 42, now(), now()),
(151, '猫眼', 'DoorViewer', 42, now(), now()),
(152, '电力仪表', 'electricmeter', 45, now(), now()),
(153, '智能广播', 'IntelligentBroadcast', 2, now(), now()),
(154, '豆浆机', 'SoyMilkMaker', 66, now(), now()),
(155, '心电卡', 'ECGCard', 68, now(), now()),
(156, '体温计', 'Thermometer', 68, now(), now()),
(157, '宠物喂食机', 'PetFeeder', 78, now(), now()),
(158, '扫地机器人', 'RobotCleaner', 54, now(), now()),
(159, '广播主机', 'BroadcastController', 2, now(), now()),
(160, '流量计', 'Flowmeter', 2, now(), now()),
(161, '远程监测终端', 'RemoteTerminalUnit', 2, now(), now()),
(162, '游乐设备信号采集器', 'SignalCollector', 2, now(), now()),
(163, '体脂秤', 'BodyFatScale', 68, now(), now()),
(164, '通用网关', 'ConversionGateway', 2, now(), now()),
(165, '人脸识别门禁', 'FaceRecognition', 2, now(), now()),
(166, '报警网关', 'WarningGW', 42, now(), now()),
(167, '断路器', 'CircuitBreaker', 42, now(), now()),
(168, '电压力锅', 'PressureCooker', 66, now(), now()),
(169, '洗衣机', 'Washer', 68, now(), now()),
(170, '智能按摩椅', 'IntelligentMassageChair', 68, now(), now()),
(171, '人脸识别能力模型', 'FaceRecognitionCapabilityModel', 42, now(), now()),
(172, '电水壶', 'ElectricKettle', 66, now(), now()),
(173, '网络存储器', 'NAS', 106, now(), now()),
(174, '电梯集采盒', 'ElevatorCollectingBox', 2, now(), now()),
(175, '养生壶', 'HealthPreservingPot', 66, now(), now()),
(176, '面包机', 'BreadMachine', 66, now(), now()),
(177, '电弧灭弧', 'ArcExtinguishing', 2, now(), now()),
(178, '电梯门体状态探测传感器', 'ElevatorStatusSensor', 2, now(), now()),
(179, '电梯平层位置探测传感器', 'ElevatorPositionSensor', 2, now(), now()),
(180, '电梯人体探测传感器', 'ElevatorBodySensor', 2, now(), now()),
(181, '电梯加速度探测传感器', 'ElevatorAccelerationSensor', 2, now(), now()),
(182, '倾角传感器', 'TiltSensor', 2, now(), now()),
(183, '考勤机', 'AttendanceMachine', 19, now(), now()),
(184, '门口机', 'OutdoorStation', 42, now(), now()),
(185, '无人货柜', 'Counter', 2, now(), now()),
(186, '报警开关', 'AlarmSwitch', 42, now(), now()),
(187, '温湿度检测', 'TemperatureHumidityDetector', 16, now(), now()),
(189, '微波人体探测器', 'MicrowaveDetector', 2, now(), now()),
(190, '自定义品类', 'CustomCategory', NULL, now(), now()),
(191, '智能电表', 'SmartElectricityMeter', 58, now(), now()),
(192, '智能水表', 'SmartWaterMeter', 58, now(), now()),
(193, '压力报警器', 'PressureAlarm', 42, now(), now()),
(194, '液位传感器', 'LiquidLevelAlarm', 42, now(), now()),
(195, '地锁', 'ParkingLock', 2, now(), now()),
(196, '水质检测终端', 'WaterMonitoring', 16, now(), now()),
(197, '胶囊咖啡机', 'CapsuleCoffeeMachine', 66, now(), now()),
(198, '温湿度采集单元', 'TempHumiUnit', 42, now(), now()),
(199, '危险报警器', 'HazardWarningLamp', 42, now(), now()),
(200, '液位计', 'liquidometer', 16, now(), now()),
(201, '网络摄像机', 'InternetProtocolCamera', 2, now(), now()),
(202, '燃气表', 'GasMeter', 15, now(), now()),
(203, '环境噪音监测', 'EnvironmentalNoiseMonitor', 16, now(), now()),
(204, '扬尘监测', 'DustMonitor', 16, now(), now()),
(205, '手动求救报警', 'AlarmButton', 2, now(), now()),
(206, '电视机', 'Television', 63, now(), now()),
(207, '非机动车充电桩', 'ChargingPile', 2, now(), now()),
(208, '电磁炉', 'InductionCooker', 66, now(), now()),
(209, '定位器', 'Locator', 2, now(), now()),
(210, '位移监控器', 'DisplacementMonitor', 2, now(), now()),
(211, '烹饪机器人', 'AutomaticCooker', 66, now(), now()),
(213, '智能生活SOC', 'SOCSmartLife', NULL, now(), now()),
(214, 'SoC插座', 'SOCOutlet', 213, now(), now()),
(215, 'SoC单孔插座', 'SingleSlotOutlet', 214, now(), now()),
(216, '电子血压计', 'Sphygmomanometer', 68, now(), now()),
(217, '车位检测器', 'ParkingDetector', 42, now(), now()),
(218, '车位锁', 'ParkingLotBarrier', 42, now(), now()),
(219, '烤箱', 'Oven', 66, now(), now()),
(220, '智能消防栓', 'SmartFireHydrants', 17, now(), now()),
(221, '图像采集设备', 'ImageCaptureDevice', 45, now(), now()),
(222, '智能电力', 'ElectricPower', NULL, now(), now()),
(223, '断电监控', 'OffVoltageMonitor', 2, now(), now()),
(224, '电动摩托车', 'ElectricMotorcycle', 78, now(), now()),
(225, '消毒柜', 'Sterilizer', 66, now(), now()),
(227, '取餐柜', 'FoodDispenser', 66, now(), now()),
(228, '计价秤', 'PricingScale', 78, now(), now()),
(231, '场景面板', 'Scene', 58, now(), now()),
(233, '嵌入式电蒸箱', 'EmbeddedSteamer', 66, now(), now()),
(234, '音箱', 'Audio', 78, now(), now()),
(235, '震动传感器', 'VibrationSensor', 42, now(), now()),
(236, '用电安全探测器', 'ElectricSafetyDetector', 2, now(), now()),
(237, '滴定泵', 'TitrantPump', 42, now(), now()),
(238, '空气能热水器', 'AirEnergyHeater', 63, now(), now()),
(239, '茶吧机', 'TeaBar', 66, now(), now()),
(240, '裁床', 'CuttingMachine', 2, now(), now()),
(241, '智能农业', 'SmartAgriculture', NULL, now(), now()),
(242, '种植', 'Plant', 241, now(), now()),
(243, '林业', 'Forestry', 241, now(), now()),
(244, '畜牧', 'Stockbreeding', 241, now(), now()),
(245, '水产', 'Aquatic', 241, now(), now()),
(247, '三相电表', 'ThreePhaseMeter', 58, now(), now()),
(248, '全屋边缘网关', 'HomeLinkEdgeGateway', 106, now(), now()),
(249, '壁挂炉', 'WallHungGasBoiler', 66, now(), now()),
(250, '吊扇灯', 'CeilingFanLamp', 58, now(), now()),
(251, '风速传感器', 'WindSensor', 241, now(), now()),
(252, '可溶性盐传感器', 'SolubleSensor', 241, now(), now()),
(253, '二氧化碳检测器', 'DioxideDetector', 241, now(), now()),
(254, '营养液流速监测器', 'FlowDetection', 241, now(), now()),
(255, '酸碱度检测计', 'PHDetector', 241, now(), now()),
(256, '有害气体检测器', 'ToxicGas', 241, now(), now()),
(257, '光照传感器', 'LightEnsor', 241, now(), now()),
(258, '智慧建筑', 'Building', NULL, now(), now()),
(259, '人脸门禁', 'FaceServer', 258, now(), now()),
(260, '道闸一体机', 'ParkOverAll', 258, now(), now()),
(261, '地磁车位监测器', 'ParkMagnetism', 258, now(), now()),
(262, '九合一环境传感器', 'EnvSensor', 258, now(), now()),
(263, '车位传感器', 'ParkHDDetectMachine', 258, now(), now()),
(264, '猪参数采集器', 'PigDataReader', 241, now(), now()),
(265, '电子纸桌签', 'epd_table', 19, now(), now()),
(266, '侧窗', 'SideWindow', 242, now(), now()),
(267, '水肥一体机', 'WaterAndFertilizerMachine', 242, now(), now()),
(268, '二氧化碳发生装置', 'CarbonDioxideGeneratingDevice', 242, now(), now()),
(269, '补光灯', 'FillLight', 242, now(), now()),
(270, '热风机', 'HotAirBlower', 242, now(), now()),
(271, '地源热泵', 'GroundSourceHeatPump', 242, now(), now()),
(272, '湿帘', 'WetCurtain', 242, now(), now()),
(273, '内保温帘幕', 'InnerInsulationCurtain', 242, now(), now()),
(274, '外遮荫帘幕', 'OutsideShadeCurtain', 242, now(), now()),
(275, '环流风机', 'CirculatingFan', 242, now(), now()),
(276, '侧风机', 'SideFan', 242, now(), now()),
(277, '天窗', 'SkyWindow', 242, now(), now()),
(278, '摄像头边缘节点\t', 'VisionAccessNode', 87, now(), now()),
(279, '超声车位检测器', 'ParkWNC', 258, now(), now()),
(280, '特征摄像头', 'FeatureCamera', 258, now(), now()),
(281, '扫脸娃娃机', 'BrushFace', 258, now(), now()),
(282, '客流量传感器', 'PeopleFlow', 258, now(), now()),
(283, '客群识别设备', 'FaceIdentification', 258, now(), now()),
(284, '停车小票机设备', 'TicketMachine', 258, now(), now()),
(285, '智能蜂箱', 'SmartHives', 241, now(), now()),
(286, '电子标签', 'EpdTable', 78, now(), now()),
(287, '中控屏', 'LocalControlCenter', 78, now(), now()),
(288, '红外遥控器', 'IRRemoteController', 78, now(), now()),
(289, '寄存器', 'Register', 241, now(), now()),
(290, '速通门', 'QuickAccessDoor', 258, now(), now()),
(291, '指纹门禁', 'FingerPrintDoor', 258, now(), now()),
(292, '余位显示屏', 'ParkLed', 258, now(), now()),
(293, '导购屏', 'GuideScreen', 258, now(), now()),
(294, '路政设备', 'GovernmentLed', 258, now(), now()),
(295, '手表', 'Watch', 78, now(), now()),
(296, '精准时空摄像头', 'PreciseTimeSpaceCamera', 16, now(), now()),
(297, '智能巡护', 'SmartPatrol', 241, now(), now()),
(298, '环境监测', 'EnvironmentMonitoring', 241, now(), now()),
(299, '猫眼摄像头', 'Cateyecamera', 42, now(), now()),
(301, '智能园区', 'campus', NULL, now(), now()),
(302, 'N4设备', 'N4DeviceType', 258, now(), now()),
(304, '车牌抓拍', 'Car_Detector_Cam', 258, now(), now()),
(305, 'lora单灯', 'loraLight', 301, now(), now()),
(306, '网关-园区', 'Gatewaycampus', 301, now(), now()),
(307, '土壤传感器', 'Soilsensor', 301, now(), now()),
(308, '车牌抓拍-ib', 'capture', 258, now(), now()),
(309, '单路窗帘开关', 'Curtainswitch', 301, now(), now()),
(310, '场景面板开关', 'Sceneswitch2', 301, now(), now()),
(311, '灌溉系统', 'irrigation', 18, now(), now()),
(312, '茶台', 'Teatable', 78, now(), now()),
(313, '智能窗帘', 'IntelligentCurtain', 78, now(), now()),
(314, '气象站监控仪', 'MeteorologicalStation', 301, now(), now()),
(315, '室内温度传感器', 'CurrentTemperature', 301, now(), now()),
(316, '入墙开关2', 'PowerSwitch2', 301, now(), now()),
(319, 'VOC感应器', 'VOCSensor', 106, now(), now()),
(320, '制冰机', 'Ice_machine', 66, now(), now()),
(322, '带计量功能插座', 'Metering_socket', 58, now(), now()),
(323, '灯控开关', 'Lamp', 58, now(), now()),
(324, '窗帘电机', 'Curtain_motor', 42, now(), now()),
(325, '家居调光面板', 'Dimming_panel', 58, now(), now()),
(326, '环境检测盒子', 'air_sensor', 54, now(), now()),
(327, '智能颈部按摩仪', 'Smart_Neck_Massage', 68, now(), now()),
(328, '智能拳靶', 'SmartBoxingTarget', 68, now(), now()),
(329, '智能洁面仪', 'SmartCleanFace', 68, now(), now()),
(330, '水浸传感器', 'water_logging', 106, now(), now()),
(331, '烟感传感器', 'Smoke_sensor', 106, now(), now()),
(332, '紧急按钮', 'emergency_button', 42, now(), now()),
(335, '气表制造', 'Gas meter manufacturing', 45, now(), now()),
(336, '空压机', 'AirCompressorMachine', 335, now(), now()),
(337, '喷涂处理', 'Spraying', 335, now(), now()),
(338, '涂胶机', 'GlueSprayingMachine', 335, now(), now()),
(339, '冲压机', 'PunchingMachine', 335, now(), now()),
(340, '室内温湿度监测设备', 'Temperatureandhumiditysensor', 301, now(), now()),
(341, '空调温控器', 'Airconditionerthermostat', 301, now(), now()),
(342, '会议平板', 'MAXHUB', 301, now(), now()),
(343, 'WiFi探针采集器', 'WiFiProbeCollector', 2, now(), now()),
(344, '铂电阻温度传感器', 'Platinum_Temperature', 45, now(), now()),
(345, '大屏投放终端', 'CoSee', 301, now(), now()),
(347, '易涝点监测设备', 'Seeper', 16, now(), now()),
(348, '窨井液位监测设备', 'ManholeLevel', 16, now(), now()),
(349, '雨量计', 'RainGauge', 16, now(), now()),
(350, '流速液位监测设备', 'FlowRate', 16, now(), now()),
(351, '视频内容分析', 'AlgorithmManagerPlatform', 87, now(), now()),
(352, '行车碰撞数据采集', 'Collision data collection', 2, now(), now()),
(353, '驾驶行为数据采集', 'Drivingbehavior', 2, now(), now()),
(354, '仓储运输环境检测设备', 'Logisticsmonitoring', 2, now(), now()),
(355, '鱼缸', 'FishTank', 78, now(), now()),
(356, '单向电流检测传感器', 'Currentdetectingsensor', 106, now(), now()),
(357, '定位终端', 'Tracker', 106, now(), now()),
(358, '锁', 'IB_Lock ', 258, now(), now()),
(359, '社区车行停车通道', 'ParkChannel', 301, now(), now()),
(360, '社区车行停车区域', 'ParkArea', 301, now(), now()),
(361, '智能水流量计', 'SmartWaterFlowMeter', 301, now(), now()),
(362, '智能燃气流量计', 'SmartGasFlowMeter', 301, now(), now()),
(363, '多功能电表', 'MultifunctionElectricityMeter', 301, now(), now()),
(364, '二维码门禁', 'QrCodeAccess', 301, now(), now()),
(365, '毛巾架', 'TowelRack', 68, now(), now()),
(366, '空气炸锅', 'Airfryer', 66, now(), now()),
(367, '软水机', 'WaterSoftener', 66, now(), now()),
(406, 'DLT645电表', 'MeterElec_Dlt645', 258, now(), now()),
(407, '面条机', 'NoodleMaker', 66, now(), now()),
(408, '密码门禁', 'PasswordAccess', 301, now(), now()),
(409, '刷卡门禁', 'CardAccess', 301, now(), now()),
(413, '门禁对讲机', 'SmartDoorIntercoms', 258, now(), now()),
(415, '传感器信号采集器', 'SensorSignalCollector', 78, now(), now()),
(416, 'HVAC外接控制器', 'HVACExtController', 78, now(), now()),
(418, '背景音乐控制器', 'BackgroundMusicController', 78, now(), now()),
(431, '停车车位', 'ParkingSpace', 301, now(), now()),
(432, '停车区域', 'ParkingArea', 301, now(), now()),
(433, '停车道闸', 'ParkingBarrier', 301, now(), now()),
(434, '停车场', 'ParkingLot', 301, now(), now()),
(437, '自动门', 'AutoDoor', 78, now(), now()),
(438, '电子围栏', 'EFence', 258, now(), now()),
(563, '灭蚊器', 'MosquitoLamp', 78, now(), now()),
(675, '割草机', 'LawnMower', 78, now(), now()),
(678, '海康边缘服务器', 'HIKVISIONEdgeServer', 301, now(), now()),
(2143, '继电器', 'Relay', 78, now(), now()),
(2184, '集成灶', 'IntegratedStove', 66, now(), now()),
(2187, '冰激凌机', 'IceCreamMaker', 66, now(), now()),
(2188, '语音温控面板', 'VoiceTemperatureControlPanel', 54, now(), now()),
(2189, '智能枕', 'SmartPillow', 68, now(), now()),
(2192, '防火门', 'FireDoor', 17, now(), now()),
(2193, '干衣机', 'Dryer', 78, now(), now()),
(2194, '应急照明灯', 'EmergencyLight', 17, now(), now()),
(2195, '智能消防水炮', 'FireWaterCannon', 17, now(), now()),
(2196, '智能消防炮', 'FireCannon', 17, now(), now()),
(2197, '智能垃圾桶', 'SmartDustbin', 2, now(), now()),
(2198, '正压送风机', 'PressureBlower', 17, now(), now()),
(2199, '水流指示器', 'FlowIndicator', 17, now(), now()),
(2200, '电动阀', 'ElectricValve', 17, now(), now()),
(2201, '电动排烟窗', 'ExhaustWindow', 17, now(), now()),
(2202, '应急广播', 'EmerBroadcasting', 17, now(), now()),
(2203, '防火阀', 'FireValve', 17, now(), now()),
(2215, '智能电梯', 'SmartElevator', 258, now(), now()),
(2216, '智能燃气表', 'SmartGasMeter', 78, now(), now()),
(2221, '电动汽车充电站', 'ElectricVehicleChargingStation', 258, now(), now()),
(2224, '梯控', 'ElevatorController', 301, now(), now()),
(2226, '食物烘干机', 'FoodDehydrator', 66, now(), now()),
(2227, '艾灸仪', 'MoxibustionApparatus', 68, now(), now()),
(2228, '智能VR类设备', 'VREquipment', 258, now(), now()),
(2229, '智能猫砂盆', 'IntelligentLitterBox', 78, now(), now()),
(2242, '网络硬盘录像机', 'NVR', 42, now(), now()),
(2243, '智能分类垃圾桶', 'SmartWasteSortingDustBin', 78, now(), now()),
(2254, '谷物碾磨机', 'GrainMill', 66, now(), now()),
(2261, '花洒', 'ShowerHead', 78, now(), now()),
(2262, '二维码门禁机', 'QrCodeAccessControl', 301, now(), now()),
(2263, '车辆主动维护', 'ActiveVehMaintenance', 2, now(), now()),
(2264, '智能车机', 'SmartTox', 2, now(), now()),
(2265, '智能后视镜', 'SmartRearviewMirror', 2, now(), now()),
(2268, '可视对讲机门口机', 'VideoIntercomDoor', 301, now(), now()),
(2269, '蓝牙门禁', 'BluetoothAccess', 301, now(), now()),
(2291, '投影仪', 'Projector', 78, now(), now()),
(2294, '人脸识别机', 'FaceRecognizeDevice', 87, now(), now()),
(2296, '广告屏', 'AdvertTerminal', 301, now(), now()),
(2298, '农田记录仪', 'FarmRecorder', 241, now(), now()),
(2300, '马桶盖', 'ToiletLid', 78, now(), now()),
(2306, '龙头', 'Faucet', 78, now(), now()),
(2310, '通断器', 'Breaker', 58, now(), now()),
(2311, '变频器', 'Inverter', 46, now(), now()),
(2312, '伺服驱动器', 'ServoDriver', 46, now(), now()),
(2313, '升降桌', 'LiftTable', 78, now(), now()),
(2317, '多功能门禁', 'MultiAccessControl', 301, now(), now()),
(2318, '机械控制阀', 'MechanicalControlValve', 78, now(), now()),
(2322, '可视门铃', 'VideoDoorbell', 42, now(), now()),
(2328, '数字门店', 'DigitalShop', 102, now(), now()),
(2329, '语音助手', 'SpeechHelper', 2328, now(), now()),
(2712, '多功能停车摄像头', 'MultiParkingCamera', 301, now(), now()),
(2743, '厌氧池', 'AnaerobicPoo', 16, now(), now()),
(2744, '缺氧池缺氧池', 'AnoxicPooAnoxicPool', 16, now(), now()),
(2745, '好氧池', 'AerobicPool', 16, now(), now()),
(2746, '调节池调节池', 'RegulatorPool', 16, now(), now()),
(2747, '二沉池', 'SecondSedimentationPool', 16, now(), now()),
(2748, '接触氧化池', 'ContactOxidationPool', 16, now(), now()),
(2749, '泵阀', 'PumpValve', 16, now(), now()),
(2750, '加压泵', 'PressurePump', 16, now(), now()),
(2954, '国标网络硬盘录像机', 'GBNVR', 42, now(), now()),
(2957, '可视宠物喂食器', 'LVPetFeeder', 42, now(), now()),
(2958, '可视门锁', 'LVLock', 42, now(), now());


INSERT INTO unit (symbol, name) VALUES
('L/min', '升每分钟'),
('mg/kg', '毫克每千克'),
('NTU', '浊度'),
('pH', 'PH值'),
('dS/m', '土壤EC值'),
('W/㎡', '太阳总辐射'),
('mm/hour', '降雨量'),
('var', '乏'),
('cP', '厘泊'),
('aw', '饱和度'),
('pcs', '个'),
('cst', '厘斯'),
('bar', '巴'),
('ppt', '纳克每升'),
('ppb', '微克每升'),
('uS/cm', '微西每厘米'),
('N/C', '牛顿每库仑'),
('V/m', '伏特每米'),
('ml/min', '滴速'),
('mmHg', '毫米汞柱'),
('mmol/L', '血糖'),
('mm/s', '毫米每秒'),
('turn/m', '转每分钟'),
('count', '次'),
('gear', '档'),
('stepCount', '步'),
('Nm3/h', '标准立方米每小时'),
('kV', '千伏'),
('kVA', '千伏安'),
('kVar', '千乏'),
('uw/cm2', '微瓦每平方厘米'),
('只', '只'),
('%RH', '相对湿度'),
('m³/s', '立方米每秒'),
('kg/s', '公斤每秒'),
('r/min', '转每分钟'),
('t/h', '吨每小时'),
('KCL/h', '千卡每小时'),
('L/s', '升每秒'),
('Mpa', '兆帕'),
('m³/h', '立方米每小时'),
('kvarh', '千乏时'),
('μg/L', '微克每升'),
('kcal', '千卡路里'),
('GB', '吉字节'),
('MB', '兆字节'),
('KB', '千字节'),
('B', '字节'),
('μg/(d㎡·d)', '微克每平方分米每天'),
('', '无'),
('ppm', '百万分率'),
('pixel', '像素'),
('Lux', '照度'),
('grav', '重力加速度'),
('dB', '分贝'),
('%', '百分比'),
('lm', '流明'),
('bit', '比特'),
('g/mL', '克每毫升'),
('g/L', '克每升'),
('mg/L', '毫克每升'),
('μg/m³', '微克每立方米'),
('mg/m³', '毫克每立方米'),
('g/m³', '克每立方米'),
('kg/m³', '千克每立方米'),
('nF', '纳法'),
('pF', '皮法'),
('μF', '微法'),
('F', '法拉'),
('Ω', '欧姆'),
('μA', '微安'),
('mA', '毫安'),
('kA', '千安'),
('A', '安培'),
('mV', '毫伏'),
('V', '伏特'),
('ms', '毫秒'),
('s', '秒'),
('min', '分钟'),
('h', '小时'),
('day', '日'),
('week', '周'),
('month', '月'),
('year', '年'),
('kn', '节'),
('km/h', '千米每小时'),
('m/s', '米每秒'),
('″', '秒'),
('′', '分'),
('°', '度'),
('rad', '弧度'),
('Hz', '赫兹'),
('μW', '微瓦'),
('mW', '毫瓦'),
('kW', '千瓦特'),
('W', '瓦特'),
('cal', '卡路里'),
('kW·h', '千瓦时'),
('Wh', '瓦时'),
('eV', '电子伏'),
('kJ', '千焦'),
('J', '焦耳'),
('℉', '华氏度'),
('K', '开尔文'),
('t', '吨'),
('°C', '摄氏度'),
('mPa', '毫帕'),
('hPa', '百帕'),
('kPa', '千帕'),
('Pa', '帕斯卡'),
('mg', '毫克'),
('g', '克'),
('kg', '千克'),
('N', '牛'),
('mL', '毫升'),
('L', '升'),
('mm³', '立方毫米'),
('cm³', '立方厘米'),
('km³', '立方千米'),
('m³', '立方米'),
('h㎡', '公顷'),
('c㎡', '平方厘米'),
('m㎡', '平方毫米'),
('k㎡', '平方千米'),
('㎡', '平方米'),
('nm', '纳米'),
('μm', '微米'),
('mm', '毫米'),
('cm', '厘米'),
('dm', '分米'),
('km', '千米'),
('m', '米');