version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: iot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iot_demo
      MYSQL_USER: iot
      MYSQL_PASSWORD: iot123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  influxdb:
    image: influxdb:2.7
    container_name: iot-influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=iot-org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=iot-token
    volumes:
      - influxdb_data:/var/lib/influxdb2

  redis:
    image: redis:7.2
    container_name: iot-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  emqx:
    image: emqx/emqx:5.5.0
    container_name: iot-emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
    environment:
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=public
    volumes:
      - emqx_data:/opt/emqx/data

volumes:
  mysql_data:
  influxdb_data:
  redis_data:
  emqx_data:
